version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip i nstall --upgrade pip
      - pip install cfn-lint
  check-cloudformation:
    commands:
      - cfn-lint Lab_1/cloudformation.yaml