version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install --upgrade pip
      - pip install cfn-lint
  build:
    commands:
      - cfn-lint Lab_2/cloudformation.yaml