AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a VPC with Public and Private
  Subnets, NAT Gateway, and EC2 Instances.

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: test
      ImageId: ami-0866a3c8686eaeeba
      SecurityGroupIds: ["sg-0440edb965d86469b"]